### ISSUE TITLE
Logo proposal!

### ISSUE THREAD

**Issue by radudang** [yussan/seal-middleware#3]
Hello! I made that logo for you.I hope you will like it.Regards!

![seal-png](https://user-images.githubusercontent.com/36233576/38233083-090622a4-3722-11e8-93ba-51c86f74be03.png)
![sealico-png](https://user-images.githubusercontent.com/36233576/38233089-0d34f9fe-3722-11e8-8dcb-1be43ceaa859.png)

Below you can find the Gdrive with all the files that you need:
https://drive.google.com/open?id=1_9Z4GnC_PqqGAE3eVdkbougTlIIRc1wi

**Comment by yussan** [comment]
amazing, i love it, 
I like the design, I will implement for this project,
thanks

**Comment by yussan** [comment]
logo has been activated via commit https://github.com/yussan/seal-middleware/commit/7596940258644aa4467f427f282295cf3c470a74
